apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - image: provectuslabs/kafka-ui
        name: kafka-ui
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka:9093"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "zookeeper:2181"  

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer  
  ports:
  - name: "kafka-ui"
    port: 8080
  selector:
    app: kafka-ui
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: bitnami/kafka
        name: kafka
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"    
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_LISTENERS
          value: "CLIENT://:9092,EXTERNAL://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "CLIENT://kafka:9092,EXTERNAL://kafka:9093"  
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "CLIENT"
          
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer  
  ports:
  - name: "kafka"
    port: 9093
  selector:
    app: kafka
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper
        name: zookeeper
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: NodePort  
  ports:
  - name: "zookeeper"
    port: 2181
  selector:
    app: zookeeper    
