apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - image: provectuslabs/kafka-ui
        name: kafka-ui
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka:9093"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "zookeeper:2181"  

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer  
  ports:
  - name: "kafka-ui"
    port: 8080
  selector:
    app: kafka-ui
