apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper
        name: zookeeper
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: LoadBalancer  
  ports:
  - name: "zookeeper"
    port: 2181
  selector:
    app: zookeeper
